               PROJECT-HOSPITAL MANAGEMENT SYSTEM 
                                            --PRITHIVIRAJ S

SELECT * FROM DOCTORS_HMS;
SELECT * FROM PATIENTS_HMS;
SELECT * FROM ROOMS_HMS;
SELECT * FROM ROOMALLOC_HMS;
SELECT * FROM BILLS_HMS;
=============================================================================

--CREATING TRIGGER TO MONITOR ROOM ALLOCATION TABLE ...
SET SERVEROUTPUT ON;
CREATE TABLE XX_R_INFO
(
USER_NAME VARCHAR(20),
DATE_TIME VARCHAR(20),
OPERATION VARCHAR(20)
);
--DROP TABLE XX_R_INFO;
CREATE OR REPLACE TRIGGER ROOM
BEFORE INSERT OR DELETE OR UPDATE ON ROOMALLOC_HMS
FOR EACH ROW
ENABLE
DECLARE
      R_USER VARCHAR(20);
      R_DATE_TIME VARCHAR(20);
BEGIN
    SELECT USER,TO_CHAR(SYSDATE,'DD/MON/YYYY HH24:MI:SS') INTO  R_USER,R_DATE_TIME FROM DUAL;
IF INSERTING THEN
    INSERT INTO XX_R_INFO(USER_NAME,DATE_TIME,OPERATION)
    VALUES(R_USER,R_DATE_TIME,'INSERT');
ELSIF DELETING THEN
    INSERT INTO XX_R_INFO(USER_NAME,DATE_TIME,OPERATION)
    VALUES(R_USER,R_DATE_TIME,'DELETE');
ELSIF UPDATING THEN
    INSERT INTO XX_R_INFO(USER_NAME,DATE_TIME,OPERATION)
    VALUES(R_USER,R_DATE_TIME,'UPDATED');
END IF;
END;
SELECT * FROM XX_R_INFO;
====================================================================================
-- PRAGMA EXCEPTION HANDLING FOR PATIENT TO CHECK AVAILABILITY OF DEPARTMENT... 
DECLARE
     EX_DEPT EXCEPTION;
     DEPT VARCHAR(20):=&K;
     PRAGMA EXCEPTION_INIT (EX_DEPT,-20020);
BEGIN
     IF DEPT = 'ENT' THEN 
         DBMS_OUTPUT.PUT_LINE('YUP!!'||' '||DEPT||' '||'TREATMENT IS AVAILABLE HERE..U CAN VISIT');
     ELSIF DEPT = 'SURGERY' THEN
         DBMS_OUTPUT.PUT_LINE('YUP!!'||' '||DEPT||' '||'TREATMENT IS AVAILABLE HERE..U CAN VISIT');
      ELSIF DEPT = 'CARDIOLOGY' THEN
         DBMS_OUTPUT.PUT_LINE('YUP!!'||' '||DEPT||' '||'TREATMENT IS AVAILABLE HERE..U CAN VISIT');
      ELSIF DEPT = 'NEUROLOGY' THEN
         DBMS_OUTPUT.PUT_LINE('YUP!!'||' '||DEPT||' '||'TREATMENT IS AVAILABLE HERE..U CAN VISIT');
      ELSIF DEPT = 'CHIROPACTOR' THEN
         DBMS_OUTPUT.PUT_LINE('YUP!!'||' '||DEPT||' '||'TREATMENT IS AVAILABLE HERE..U CAN VISIT');
      ELSIF DEPT = 'DERMATOLOGY' THEN
         DBMS_OUTPUT.PUT_LINE('YUP!!'||' '||DEPT||' '||'TREATMENT IS AVAILABLE HERE..U CAN VISIT');
      ELSIF DEPT = 'Gynecologist' THEN
         DBMS_OUTPUT.PUT_LINE('YUP!!'||' '||DEPT||' '||'TREATMENT IS AVAILABLE HERE..U CAN VISIT');
      ELSIF DEPT = 'Oncologist' THEN
         DBMS_OUTPUT.PUT_LINE('YUP!!'||' '||DEPT||' '||'TREATMENT IS AVAILABLE HERE..U CAN VISIT');
      ELSIF DEPT = 'Pediatrician' THEN
         DBMS_OUTPUT.PUT_LINE('YUP!!'||' '||DEPT||' '||'TREATMENT IS AVAILABLE HERE..U CAN VISIT');
      ELSE 
         RAISE_APPLICATION_ERROR(-20020,'OOPS!!'||' '||DEPT||' '|| 'TREATMENT IS NOT AVAILABLE HERE.. SORRY!!');
      END IF;
      EXCEPTION WHEN EX_DEPT THEN
         DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;
=======================================================================================================
--CREATING CURSOR TO FETCH PATIENT DEPARTMENT ,PATIENT ID AND NAME ACCORDING TO PATIENT STATUS

DECLARE
     STATUS VARCHAR(20):=&G;
     CURSOR PATIENT_DETAILS 
     IS
     SELECT D_DEPT,P_ID,P_NAME
     FROM PATIENTS_HMS
     WHERE P_STATUS = STATUS;
BEGIN 
     FOR L_IDX IN PATIENT_DETAILS
     LOOP
        DBMS_OUTPUT.PUT_LINE('ACCORDING TO GIVEN STATUS-'||' '||'PATIENT DEPARTMENT '||L_IDX.D_DEPT|| ' '||'AND NAME '||L_IDX.P_NAME||' '||'AND ID'||' '||L_IDX.P_ID);
     END LOOP;
     DBMS_OUTPUT.PUT_LINE('ENTER VALID STATUS');
     
END;
=========================================================================
----CREATING PARAMETERIZED CURSOR TO FETCH PATIENT ID AND NAME ACCORDING TO PARTICULAR DEPARTMENT

DECLARE
      PNAME VARCHAR(20);
      PID VARCHAR(10);
      CURSOR PATIENT_DETAILS_DEPT(DEPARTMENT VARCHAR:=&D) IS
      SELECT P_ID,P_NAME FROM PATIENTS_HMS
      WHERE D_DEPT = DEPARTMENT;
BEGIN
    OPEN PATIENT_DETAILS_DEPT;
    LOOP
       FETCH PATIENT_DETAILS_DEPT INTO PID,PNAME;
       EXIT WHEN PATIENT_DETAILS_DEPT%NOTFOUND;
       DBMS_OUTPUT.PUT_LINE('ACCORDING TO GIVEN DEPARTMENT-'||' '||'PATIENT ID '||PID|| ' '||'AND NAME'||' '||PNAME);
       END LOOP;
       DBMS_OUTPUT.PUT_LINE('NO PATIENT ADMITTED IN DEPARTMENT');
       CLOSE PATIENT_DETAILS_DEPT;
END;
============================================================================================